Circumvent dlib-opencv mismatch compilation error
Avoid the following compilation failure arising from a mismatch between
particular versions of `dlib` and OpenCV (see davisking/dlib#1949):

        In file included from /usr/include/dlib/opencv.h:10,
                         from src/head_pose_estimation.hpp:5,
                         from src/head_pose_estimation.cpp:11:
        /usr/include/dlib/opencv/cv_image.h: In instantiation of ‘dlib::cv_image<pixel_type>::cv_image(cv::Mat) [with pixel_type = dlib::bgr_pixel]’:
        src/head_pose_estimation.cpp:48:46:   required from here
        /usr/include/dlib/opencv/cv_image.h:37:29: error: conversion from ‘const cv::Mat’ to non-scalar type ‘IplImage’ requested
           37 |             IplImage temp = img;