Add OpenCV header for missing definition of CV_AA
Avoid the following compilation error by adding the relevant header:

    error: ‘CV_AA’ was not declared in this scope; did you mean ‘CV_MSA’?